### ISSUE TITLE
Using network message 71 causes issue by flooding the vanilla message handler with garbage data.

### ISSUE THREAD

**Issue by harbingerofme** [SushiDevshi/HANDY#1]
The extended overlap attack does this.
Because of this weird desyncs occur.

**Comment by SushiDevshi** [comment]
Right, any other information about this?

**Comment by harbingerofme** [comment]
It's same message id as normal overlap attacks. This means the messages from extended overlap attacks get send to the normal overlap attacks.

**Comment by SushiDevshi** [comment]
Fixed in latest commit, closing the issue.
